#dataSource:
#  driverClassName: org.postgresql.Driver
#  url: jdbc:postgresql://localhost:5432/movieland
#  user: postgres
#  pass: 123456
#  maxTotal: 10
Scheduler:
  initialDelay: 14400000
  fixedDelay: 14400000